version: '3'

services:
  go-app:
    build:
      context: ../..
      dockerfile: deployments/deployment/Dockerfile
    restart: unless-stopped
    ports: [ "8080:3000" ]
    volumes:
      - .:/go/src/app
    env_file:
      - .env