services:
  go-app:
    build:
      context: ../..
      dockerfile: ../development/Dockerfile
    restart: unless-stopped
    networks:
      - development
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    volumes:
      - .:/go/src/app
    env_file:
      - .env

networks:
  development:
    driver: bridge
    name: development